### ISSUE TITLE
存在一个问题 

### ISSUE THREAD

**Issue by happynessTony** [SmallRuralDog/lyf-vue#1]
首页头部分类中最后一个分类不会被显示出来
<img width="985" alt="2017-08-14 16 09 10" src="https://user-images.githubusercontent.com/13941417/29263277-ae921c24-810a-11e7-947d-35264f0f8bf5.png">

**Comment by SmallRuralDog** [comment]
请加上分辨率和系统，我这边看是正常的

**Comment by happynessTony** [comment]
<img width="597" alt="2017-08-15 11 42 22" src="https://user-images.githubusercontent.com/13941417/29301403-80a656be-81ae-11e7-95a4-8109c8afd36f.png">

然后我在这个位置加上了5 然后就行了

<img width="512" alt="2017-08-15 11 43 53" src="https://user-images.githubusercontent.com/13941417/29301439-c528e914-81ae-11e7-9994-1579dbe33b57.png">

**Comment by yanyusheng123456** [comment]
这个放在apache上怎么访问首页？
